### ISSUE TITLE
Is there any tool for 3G UMTS cell scan?

### ISSUE THREAD

**Issue by Al3x4n** [mgp25/RF-List#1]
I'm looking for tool/project that is use USRP to scan 3G UMTS cell, and then analysis downlink broadcast cell?
Could you suggest me?

**Comment by mgp25** [comment]
Hello @Al3x4n,

As far as I know, there isn't a project to scan UMTS cells using a computer, although this should be easy to achieve. There are some alternatives for scanning and tracking different types of cells, for example [G-NetTrack Lite](https://play.google.com/store/apps/details?id=com.gyokovsolutions.gnettracklite) should work for you.

Hope it could helps you.

Best regards

**Comment by MountainLogic** [comment]
[GnuRadio](https://www.gnuradio.org/) has an add-on module [GR-GSM ](https://github.com/ptrkrysik/gr-gsm).  The add-ons (called Out of Tree or OoT in GnuRadio documentation) are not always kept up to date so you may have to use a slightly older version of GR-GSM to match, but that should not be an issue for GSM.  GnuRadio is a bit fussier to use and install, but much more flexible.

**Comment by mgp25** [comment]
@MountainLogic yep, I have GNURadio, and I have the same opinion as you. In fact, `GR-GSM` repo has already a sample app scanner for that purpose: [https://github.com/ptrkrysik/gr-gsm/blob/master/apps/grgsm_scanner](https://github.com/ptrkrysik/gr-gsm/blob/master/apps/grgsm_scanner).
